-- begin SESSIONPLANER_SESSIONS
alter table SESSIONPLANER_SESSIONS add constraint FK_SESSIONPLANER_SESSIONS_ON_SPEAKER foreign key (SPEAKER_ID) references SESSIONPLANER_SPEAKER(ID)^
create index IDX_SESSIONPLANER_SESSIONS_ON_SPEAKER on SESSIONPLANER_SESSIONS (SPEAKER_ID)^
-- end SESSIONPLANER_SESSIONS
-- begin SESSIONPLANER_SPEAKER
create unique index IDX_SESSIONPLANER_SPEAKER_UNIQ_EMAIL on SESSIONPLANER_SPEAKER (EMAIL) ^
-- end SESSIONPLANER_SPEAKER
